theme: jekyll-theme-minimal
author: Cevdet Arda Haran
email: cevdet@tutamail.com
title: 3D Boxes Background
description: "Animated Countdown Frontend Website Project."
keywords: "Cevdet Arda Haran, Cennedy, Animated Countdown, animation, countdown"
baseurl: "/animated-countdown"
url: "https://cevdetardaharan.github.io/animated-countdown"
twitter_username: cevdetardaharan  
github_username:  cevdetardaharan
